/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;



import datos.AlmacenamientoEstudiantes;
import datos.AlmacenamientoCarreras;
import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.net.URL;
import java.util.List;
import java.util.Optional;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import logica.Carrera;
import logica.Estudiante;

/**
 *
 * @author jonat
 */
public class DlgEstudiante extends javax.swing.JDialog {
    private AlmacenamientoEstudiantes almEstudiantes;
    private AlmacenamientoCarreras almCarreras;
    private List<Estudiante> modelo;

    
    


    /**
     * Creates new form DlgGestionAutos
     */
     public DlgEstudiante(JFrame parent, AlmacenamientoEstudiantes almEstudiantes, AlmacenamientoCarreras almCarreras) {
    super(parent, true);
    this.almEstudiantes = almEstudiantes;
    this.almCarreras = almCarreras; 

    initComponents();  

    setButtonIcon(btnInsertar, "/img/insert.png");
    setButtonIcon(btnEditar, "/img/editar.png");
    setButtonIcon(btnEliminar, "/img/eliminar.png");

    setWindowIcon();

    // Inicializar la lista de estudiantes
    modelo = almEstudiantes.listarTodos();
    cargarTabla(modelo);
}

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiante = new javax.swing.JTable();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEstudiante);

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void setButtonIcon(javax.swing.JButton button, String resourcePath) {
    java.net.URL iconURL = getClass().getResource(resourcePath);
    if (iconURL != null) {
        button.setIcon(new javax.swing.ImageIcon(iconURL));
    } else {
        System.err.println("No se encontró el recurso: " + resourcePath);
    }
}

private void setWindowIcon() {
        URL url = getClass().getResource("/img/icon.png");
        if (url != null) {
            Image icon = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(icon); // ← Esto aplica el ícono a la ventana
        } else {
            System.err.println("No se encontró el ícono /imagenes/logo.png");
        }
    }

   private void cargarTabla(List<Estudiante> lista) {
     if (lista == null) {
        lista = List.of(); // Evita null
    }

    modelo = lista; // Actualiza la lista modelo

    // Crear un modelo de tabla con columnas definidas y no editables
    DefaultTableModel m = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Nombre", "Carnet", "Carrera"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    // Rellenar la tabla
    for (Estudiante e : lista) {
        // Obtener el nombre de la carrera usando Optional
        String nombreCarrera = almCarreras.buscarPorId(e.getIdCarrera())
                                         .map(Carrera::getNomCarrera)
                                         .orElse("Desconocida");

        m.addRow(new Object[]{
            e.getNombre(),
            e.getCarnet(),
            nombreCarrera
        });
    }

    tblEstudiante.setModel(m); // Actualiza la tabla

    if (txtCant != null) { // Evita NullPointerException
        txtCant.setText(String.valueOf(lista.size()));
    }

}



    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
     DlgNuevoEstudiante dlg = new DlgNuevoEstudiante((java.awt.Frame) this.getParent(), true);
    dlg.initInsertar(almEstudiantes, almCarreras);
    dlg.setVisible(true);
    cargarTabla(almEstudiantes.listarTodos());

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          cargarTabla(modelo);
    }//GEN-LAST:event_formWindowActivated

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                                             
     int fila = tblEstudiante.getSelectedRow();
    if (fila >= 0) {
        Estudiante seleccionado = modelo.get(fila);
        almEstudiantes.eliminarPorCarnet(seleccionado.getCarnet());
        cargarTabla(almEstudiantes.listarTodos());
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un estudiante para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int fila = tblEstudiante.getSelectedRow();
    
    if (fila >= 0) {
        // Obtener el estudiante seleccionado
        Estudiante seleccionado = modelo.get(fila);

        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        DlgNuevoEstudiante dlg = new DlgNuevoEstudiante((Frame) parentWindow, true);


        // Inicializar el diálogo con los datos del estudiante
        dlg.initEditar(seleccionado, almEstudiantes, almCarreras);

        // Mostrar el diálogo
        dlg.setVisible(true);

        // Refrescar la tabla después de cerrar el diálogo
        cargarTabla(almEstudiantes.listarTodos());
    } else {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un estudiante para editar", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        
    String texto = txtBuscar.getText();
    List<Estudiante> filtrados = almEstudiantes.filtrarPorNombre(texto);
    cargarTabla(filtrados);
    txtCant.setText(String.valueOf(filtrados.size()));




    }//GEN-LAST:event_txtBuscarKeyReleased


    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
    EventQueue.invokeLater(() -> {
        AlmacenamientoEstudiantes almEstudiantes = new AlmacenamientoEstudiantes();
        AlmacenamientoCarreras almCarreras = new AlmacenamientoCarreras();
        DlgEstudiante dialog = new DlgEstudiante(new JFrame(), almEstudiantes, almCarreras);
        dialog.setVisible(true);
    });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblEstudiante;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
