/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import datos.AlmacenamientoBeneficios;
import datos.AlmacenamientoEstudiantes;
import java.util.List;
import logica.Beneficio;
import logica.Estudiante;
import datos.AlmacenamientoBeneficiosEstudiantes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.BeneficioEstudiante;
/**
 *
 * @author helde
 */
public class FrmAsignarBeneficios extends javax.swing.JFrame {
private AlmacenamientoEstudiantes almacenamientoEstudiantes = new AlmacenamientoEstudiantes();
private AlmacenamientoBeneficios almacenamientoBeneficios = new AlmacenamientoBeneficios();
private AlmacenamientoBeneficiosEstudiantes almacenamientoBeneficiosEstudiantes = new AlmacenamientoBeneficiosEstudiantes();

    /**
     * Creates new form FrmAsignarBeneficios
     */
    public FrmAsignarBeneficios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedulaEstudiante = new javax.swing.JLabel();
        cmbxCedEstBene = new javax.swing.JComboBox<>();
        lblIdBeneficios = new javax.swing.JLabel();
        cmbxIdBeneficios = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsigBene = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCedulaEstudiante.setText("Cedula Estudiante");

        cmbxCedEstBene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblIdBeneficios.setText("IdBeneficios");

        cmbxIdBeneficios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        tblAsigBene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Id Beneficio"
            }
        ));
        jScrollPane1.setViewportView(tblAsigBene);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblCedulaEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbxCedEstBene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblIdBeneficios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbxIdBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(btnAsignar)
                .addGap(60, 60, 60)
                .addComponent(btnQuitar)
                .addContainerGap(103, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbxCedEstBene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdBeneficios)
                        .addComponent(cmbxIdBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAsignar)
                        .addComponent(btnQuitar))
                    .addComponent(lblCedulaEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
      String cedula = (String) cmbxCedEstBene.getSelectedItem();
        int idBeneficio = Integer.parseInt((String) cmbxIdBeneficios.getSelectedItem());

    try {
        almacenamientoBeneficiosEstudiantes.asignar(cedula, idBeneficio, almacenamientoEstudiantes, almacenamientoBeneficios);
        actualizarTabla(cedula);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        String cedula = (String) cmbxCedEstBene.getSelectedItem();
    int idBeneficio = (int) cmbxIdBeneficios.getSelectedItem();

    try {
        almacenamientoBeneficiosEstudiantes.quitar(cedula, idBeneficio);
        actualizarTabla(cedula);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnQuitarActionPerformed
    private void actualizarTabla(String cedula) {
    List<BeneficioEstudiante> lista = almacenamientoBeneficiosEstudiantes.listarPorEstudiante(cedula);
    DefaultTableModel modelo = (DefaultTableModel) tblAsigBene.getModel();
    modelo.setRowCount(0); // limpiar

    for (BeneficioEstudiante be : lista) {
        modelo.addRow(new Object[] {
            be.getCedula(),
            be.getIdBeneficio()
        });
    }
}
private void cargarComboBoxes() {
    cmbxCedEstBene.removeAllItems();
   for (Estudiante est : almacenamientoEstudiantes.listarTodos()) {
    cmbxCedEstBene.addItem(est.getCedula());
}


    cmbxIdBeneficios.removeAllItems();
    for (Beneficio ben : almacenamientoBeneficios.listarTodos()) {
      cmbxIdBeneficios.addItem(String.valueOf(ben.getIdBeneficio()));

}

}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAsignarBeneficios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAsignarBeneficios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAsignarBeneficios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAsignarBeneficios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAsignarBeneficios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbxCedEstBene;
    private javax.swing.JComboBox<String> cmbxIdBeneficios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedulaEstudiante;
    private javax.swing.JLabel lblIdBeneficios;
    private javax.swing.JTable tblAsigBene;
    // End of variables declaration//GEN-END:variables
}
