/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author helde
 */
public class FrmSistemaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmSistemaPrincipal
     */
    public FrmSistemaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionEst = new javax.swing.JButton();
        btnGestionCarre = new javax.swing.JButton();
        btnGestionBene = new javax.swing.JButton();
        btnAsignarBene = new javax.swing.JButton();
        btnPagosMensuales = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGestionEst.setText("Gestion de Estudiantes");
        btnGestionEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEstActionPerformed(evt);
            }
        });

        btnGestionCarre.setText("Gestion Carreras");
        btnGestionCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionCarreActionPerformed(evt);
            }
        });

        btnGestionBene.setText("Gestion Beneficios");
        btnGestionBene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionBeneActionPerformed(evt);
            }
        });

        btnAsignarBene.setText("Asignar Beneficios");
        btnAsignarBene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBeneActionPerformed(evt);
            }
        });

        btnPagosMensuales.setText("Pagos Mensuales");
        btnPagosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosMensualesActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnGestionEst)
                        .addGap(147, 147, 147)
                        .addComponent(btnGestionCarre)
                        .addGap(138, 138, 138)
                        .addComponent(btnGestionBene))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnAsignarBene)
                        .addGap(187, 187, 187)
                        .addComponent(btnPagosMensuales)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionEst)
                    .addComponent(btnGestionCarre)
                    .addComponent(btnGestionBene))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarBene)
                    .addComponent(btnPagosMensuales))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEstActionPerformed
        // TODO add your handling code here:
        DlgEstudiante dlg = new DlgEstudiante(this, true);
        dlg.setLocationRelativeTo(this); // Centra la nueva ventana respecto a la actual
        dlg.setVisible(true); // Muestra el dlg
        this.setVisible(false);//Esconde esta ventana
    }//GEN-LAST:event_btnGestionEstActionPerformed

    private void btnAsignarBeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBeneActionPerformed
        // TODO add your handling code here:
        FrmAsignarBeneficios frm = new FrmAsignarBeneficios(); 
        frm.setLocationRelativeTo(this); // Centra la nueva ventana respecto a la actual
        frm.setVisible(true); // Muestra la nueva ventana
        this.setVisible(false);//Esconde esta ventana
    }//GEN-LAST:event_btnAsignarBeneActionPerformed

    private void btnPagosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosMensualesActionPerformed
        // TODO add your handling code here:
        DlgPagosMensuales dlg = new DlgPagosMensuales(this, true);
        dlg.setLocationRelativeTo(this);//Centra la ventana respecto a la actual
        dlg.setVisible(true);//Muestra la nueva ventana
        this.setVisible(false);//Esconde esta ventana
        
    }//GEN-LAST:event_btnPagosMensualesActionPerformed

    private void btnGestionCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCarreActionPerformed
        // TODO add your handling code here:
        DlgCarreras dlg = new DlgCarreras(this, true);
        dlg.setLocationRelativeTo(this); // Centra el dlg como el actual
        dlg.setVisible(true); // Muestra el diálogo
        this.setVisible(false);//Esconde esta ventana
    }//GEN-LAST:event_btnGestionCarreActionPerformed

    private void btnGestionBeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionBeneActionPerformed
        // TODO add your handling code here:
        DlgBeneficios dlg = new DlgBeneficios(this, true);
        dlg.setLocationRelativeTo(this); // Centra la ventana igual al actual
        dlg.setVisible(true); // Muestra el dlg
        this.setVisible(false);//Esconde esta ventana
    }//GEN-LAST:event_btnGestionBeneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistemaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBene;
    private javax.swing.JButton btnGestionBene;
    private javax.swing.JButton btnGestionCarre;
    private javax.swing.JButton btnGestionEst;
    private javax.swing.JButton btnPagosMensuales;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
